### ISSUE TITLE
Unsupported .MD syntax

### ISSUE THREAD

**Issue by lobster2012-user** [limedocs/limedocs-wiki-converter#1]
I try to convert https://github.com/NancyFx/Nancy.wiki.git
1 [[localfile]] unsupported. I replace manually [[url]] on `[url](url)`
2.i added manually  alias  c# for highlight .js
3. Not found pdf output file. Html file looks not very good (in opera and chrome)

**Comment by yakivmospan** [comment]
@lobster2012-user `[[]]` is not supported, cause `lwc` relies on [marked](https://github.com/chjj/marked) and it can't recognize it. Please see this thread https://github.com/chjj/marked/issues/471.

Instead you can check my PR - https://github.com/limedocs/limedocs-wiki-converter/pull/3, it allows you to use full links to `.md` files in you wiki and they will be treated as page indicators.

About PDF output, make sure you did install http://wkhtmltopdf.org/downloads.html and add it to your PATH. I can see both html and pdf outputs.

**Comment by mattallty** [comment]
Closing as this seems fully replied
